version: '3'

services:
  django:
    build: .
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/app
    command: python myproject/manage.py runserver 0.0.0.0:6655

    network_mode: host
    restart: always

volumes:
  db_volume: