# Generated by Django 5.0.6 on 2024-05-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
